apiVersion: v1
kind: Service
metadata:
  labels:
    app: monitorapp
  name: monitorapp
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodeport: 3002
      protocol: TCP
  selector:
    app: monitorapp
